schema_version = "1.0.0"

id = "surfacepsycho"
version = "0.6.0"
name = "Surface Psycho"
tagline = "Surface Design in Blender"
maintainer = "Romain Guimbal"
type = "add-on"

website = "https://github.com/RomainGuimbal/SurfacePsycho/wiki"

tags = ["Modeling", "Import-Export", "Geometry Nodes"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2024 Romain Guimbal"]

# platforms = ["any", "windows-x64"]
wheels = [
  "./wheels/six-1.16.0-py3-none-any.whl",
  "./wheels/OCC-7.7.2-py3-none-any.whl",
]

[permissions]
files = "Import/export CAD files"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/*.blend1",
  "Asset Importer.py",
]