schema_version = "1.0.0"

id = "surfacepsycho"
version = "0.8.3"
name = "Surface Psycho"
tagline = "Precision Surface Design"
maintainer = "Romain Guimbal"
type = "add-on"

website = "https://github.com/RomainGuimbal/SurfacePsycho/wiki"

tags = ["Modeling", "Import-Export", "Geometry Nodes", "Add Curve"]

blender_version_min = "4.3.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2024 Romain Guimbal"]

platforms = ["windows-x64", "macos-x64", "macos-arm64", "linux-x64"]
wheels = [
  "./wheels/six-1.16.0-py2.py3-none-any.whl",
  "./wheels/cadquery_ocp_novtk-7.8.1.1.post1-cp311-cp311-win_amd64.whl",
  "./wheels/cadquery_ocp_novtk-7.8.1.1.post1-cp311-cp311-macosx_11_0_x86_64.whl",
  "./wheels/cadquery_ocp_novtk-7.8.1.1.post1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/cadquery_ocp_novtk-7.8.1.1.post1-cp311-cp311-manylinux_2_31_x86_64.whl"
]

[permissions]
files = "Import and export CAD files"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/.trunk/",
  "/.vscode/",
  "/.github/",
  "/*.zip",
  "*.blend1",
  ".gitignore",
  ".gitattributes",
  "README.md",
  "Asset Importer.py",
]