name: Build Python OCC Windows

on:
  workflow_dispatch:

jobs:
  build-occt:
    runs-on: windows-latest #${{ matrix.os }}
    steps:
      #- uses: actions/checkout@v4 
      
      - name: Restore cached occt
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
           path: D:/a/SurfacePsycho/OCCT_mon_install
           key: occinstall-${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
           lookup-only: true
      
      
      - name: download occt source #- if: ${{ matrix.wind }}
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ../
          ls
          C:\msys64\usr\bin\wget.exe -O occt-7.7.2.zip "https://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=cec1ecd0c9f3b3d2572c47035d11949e8dfa85e2;sf=zip"
          7z x occt-7.7.2.zip
          ls
      
      - name: 3rd party
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ../
          mkdir OCCT_mon_install
          ls
          cd occt-cec1ecd
          ls
          mkdir 3rdparty
          cd 3rdparty
          C:\msys64\usr\bin\wget.exe "https://download.qt.io/archive/qt/4.8/4.8.6/qt-everywhere-opensource-src-4.8.6.zip"
          C:\msys64\usr\bin\wget.exe "https://dev.opencascade.org/system/files/occt/3rdparty/ffmpeg-3.3.4-64.zip"
          C:\msys64\usr\bin\wget.exe "https://dev.opencascade.org/system/files/occt/3rdparty/VTK-6.1.0-vc14-64.zip"
          C:\msys64\usr\bin\wget.exe "https://dev.opencascade.org/system/files/occt/3rdparty/angle-gles2-2.1.0-46ad513f4e5b-vc14-64.zip"
          C:\msys64\usr\bin\wget.exe "https://dev.opencascade.org/system/files/occt/3rdparty/freetype-2.5.5-vc14-64.zip"
          C:\msys64\usr\bin\wget.exe "https://github.com/oneapi-src/oneTBB/releases/download/v2021.11.0/oneapi-tbb-2021.11.0-win.zip"
          C:\msys64\usr\bin\wget.exe "https://dev.opencascade.org/system/files/occt/3rdparty/tcltk-86-64.zip"
          7z x qt-everywhere-opensource-src-4.8.6.zip
          7z x ffmpeg-3.3.4-64.zip
          7z x VTK-6.1.0-vc14-64.zip
          7z x angle-gles2-2.1.0-46ad513f4e5b-vc14-64.zip
          7z x freetype-2.5.5-vc14-64.zip
          7z x oneapi-tbb-2021.11.0-win.zip
          7z x tcltk-86-64.zip
          ls
          
      - name: cmake configure
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run : |
          cd ../../
          ls
          cmake -DINSTALL_DIR="D:/a/SurfacePsycho/OCCT_mon_install" -DBUILD_RELEASE_DISABLE_EXCEPTIONS=OFF -D3RDPARTY_DIR="D:/a/SurfacePsycho/occt-cec1ecd/3rdparty" -DCMAKE_BUILD_TYPE=Release -B="D:/a/SurfacePsycho/occt-cec1ecd/ma_build"  -S="D:/a/SurfacePsycho/occt-cec1ecd"
          
      - name: cmake build OCCT
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run : |
          cmake --build D:/a/SurfacePsycho/occt-cec1ecd/ma_build    
      - name: prepare
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run : | 
          mv D:/a/SurfacePsycho/occt-cec1ecd/ma_build/win64/vc14/bind D:/a/SurfacePsycho/occt-cec1ecd/ma_build/win64/vc14/bin
          mv D:/a/SurfacePsycho/occt-cec1ecd/ma_build/win64/vc14/libd D:/a/SurfacePsycho/occt-cec1ecd/ma_build/win64/vc14/lib
        #cd ../
        #7z a occt_build_not_installed D:/a/SurfacePsycho/occt-cec1ecd/ma_build

     #- uses: actions/upload-artifact@v4
        #with:
          #name: occt_build_not_installed
          #path: D:/a/SurfacePsycho/occt_build_not_installed.7z
          
      - name: cmake install OCCT
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run : |
          cmake --install D:/a/SurfacePsycho/occt-cec1ecd/ma_build  
        #if: steps.cache-restore.outputs.cache-hit != 'true'
      #- name: add system path
        #run : echo "D:/a/SurfacePsycho/pythonocc-core/ma_build" >> /etc/ld.so.conf.d/occt.conf

      - name: Save cache occt build
        id: cache-save
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: D:/a/SurfacePsycho/OCCT_mon_install
          key: occinstall-${{ runner.os }}-${{ hashFiles('**/lockfiles') }}





  
  build-pyocct:
    needs: build-occt
    runs-on: windows-latest #${{ matrix.os }}
    steps:
      - name: Restore cached occt
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
           path: D:/a/SurfacePsycho/OCCT_mon_install
           key: occinstall-${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
           
      # - uses: actions/checkout@v4 
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      # - run: |
      #     python
      #     echo "PYTHONPATH=C:\hostedtoolcache\windows\Python\3.11.8\x64" >> $GITHUB_PATH
      #     echo "PYTHONPATH=C:\hostedtoolcache\windows\Python\3.11.8\x64" >> $GITHUB_ENV

      - name: install python
        run: |
          cd ../
          dir
          C:\msys64\usr\bin\wget.exe https://www.python.org/ftp/python/3.11.8/python-3.11.8-amd64.exe
          ls
          python-3.11.8-amd64 --Include_debug=1 --InstallAllUsers=1 --Include_symbols=1

      # echo "::set-env name=PYTHONPATH::C:\hostedtoolcache\windows\Python\3.11.8\x64"
      #echo "::set-env name=PYTHONPATH::home/runner/work/pythonocc-core"
      - name: setup swig
        run : |
          C:\msys64\usr\bin\wget.exe -o log "https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.1.1/swigwin-4.1.1.zip"
          7z x swigwin-4.1.1.zip
          ls
          echo "D:/a/SurfacePsycho/swigwin-4.1.1" >> $GITHUB_PATH

      - name: download pyocc source 7.7.2
        run: |
          cd ../
          ls
          C:\msys64\usr\bin\wget.exe -o log "https://github.com/tpaviot/pythonocc-core/archive/refs/tags/7.7.2.zip"
          7z x 7.7.2.zip

      - name: cmake configure
        run: |
          cd ../
          mkdir pyocc_mon_install
          cd pythonocc-core-7.7.2
          mkdir ma_build
          cmake -DOCCT_INCLUDE_DIR="D:/a/SurfacePsycho/OCCT_mon_install/inc" -DOCCT_LIBRARY_DIR="D:/a/SurfacePsycho/OCCT_mon_install/win64/vc14/lib" -DPYTHONOCC_BUILD_TYPE=Release -DPYTHONOCC_INSTALL_DIRECTORY="D:/a/SurfacePsycho/pyocc_mon_install" -DGP_PNT_HEADER_LOCATION="D:/a/SurfacePsycho/OCCT_mon_install/inc/gp_Pnt.hxx" -B="D:/a/SurfacePsycho/pythonocc-core-7.7.2/ma_build" -S="D:/a/SurfacePsycho/pythonocc-core-7.7.2"
          
          cd ../
          7z a hhhh D:/a/SurfacePsycho/pythonocc-core-7.7.2/
          ls
          
      - uses: actions/upload-artifact@v4
        with:
          name: hhhh
          path: D:/a/SurfacePsycho/hhhh.7z
          
      - name: cmake build
        run: |
          cmake --build D:/a/SurfacePsycho/pythonocc-core-7.7.2/ma_build
          echo "D:/a/SurfacePsycho/OCCT_mon_install/lib" >> $LD_LIBRARY_PATH
      - name: cmake install pythonocc
        run: |
          cmake --install D:/a/SurfacePsycho/pythonocc-core-7.7.2/ma_build
          
      - name: prepare
        run : |
          cd ../
          ls
          7z a OCC D:/a/SurfacePsycho/pyocc_mon_install
          ls
      - uses: actions/upload-artifact@v4
        with:
          name: pythonOCC
          path: D:/a/SurfacePsycho/OCC.7z
