name: Python OCC conda Windows
on:
  workflow_dispatch:

jobs:
  miniconda:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pyoccenv
          python-version: 3.11
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: install pythonocc
        run: |
          conda install -c conda-forge pythonocc-core=7.7.2
      - name: echo paths
        run: |
          cd C:/Miniconda/envs/pyoccenv
          ls
        # tree -d 
          
        # echo $(conda info --all)
          # echo Ceux qui match :
          # echo $(conda info --all | grep -i pythonocc-core)
          # echo $(conda info --all | grep -i OCC)
          # echo "PYOCCPATH=$(conda info --all  | grep -i pythonocc-core)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: OCC-wind
          path: C:/Miniconda/envs/pyoccenv/Lib/site-packages/OCC/
