name: PythonOCC conda build
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyoccenv
          python-version: 3.9
          auto-activate-base: false
      - shell: bash
        run: |
          conda info
          conda list
      - name: install pythonocc
        shell: bash
        run: |
          conda install -c conda-forge pythonocc-core=7.7.2
          echo "PYOCCPATH=$(conda info --all  | grep -i pythonocc-core)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: $PYOCCPATH
