name: Python OCC conda Linux

on:
  workflow_dispatch:

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pyoccenv
          python-version: 3.11
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: install pythonocc
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pythonocc-core=7.7.2
      - name: echo paths
        shell: bash -l {0}
        run: |
          cd /usr/share/miniconda/envs
          tree -d pyoccenv
          
        # echo $(conda info --all)
          # echo Ceux qui match :
          # echo $(conda info --all | grep -i pythonocc-core)
          # echo $(conda info --all | grep -i OCC)
          # echo "PYOCCPATH=$(conda info --all  | grep -i pythonocc-core)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: OCC-linux-sans-deps
          path: /usr/share/miniconda/envs/pyoccenv/lib/python3.9/site-packages/OCC/
